service: alexa-skill-hitch

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: eu-west-1
  memorySize: 512
  cfLogs: true

functions:
  alexaSkill:
    handler: index.handler
    description: Alexa skill to demonstrate account linking
    events:
      - alexaSkill
